// Repères historiques affichés dans la Fresque et dans les fiches (« Dans l’Histoire »).
// Événement : [début, fin ou null, titre, catégorie, portée, importance, détail]
//   catégorie G guerre · P politique · C culture/sciences · S société/économie · E épidémie/catastrophe · R religion
//   portée F France · M monde ; importance 1 majeur … 3 visible en zoom fort
// Périodes (régimes, souverains, époques) : [début, fin, nom]. Modifiez librement ce fichier.
const HISTOIRE = {
  evenements: [
    [235, 284, "Crise du IIIᵉ siècle", "P", "M", 3, "Guerres civiles et invasions dans l'Empire romain."],
    [313, null, "Édit de Milan", "R", "M", 2, "Liberté de culte accordée aux chrétiens dans l'Empire romain."],
    [395, null, "Partage de l'Empire romain", "P", "M", 3, "Séparation définitive entre Occident et Orient."],
    [406, 476, "Grandes invasions", "G", "M", 2, "Vandales, Alains, Suèves, Wisigoths, Burgondes et Francs pénètrent dans l'Empire."],
    [451, null, "Champs Catalauniques", "G", "F", 2, "Les Romains et leurs alliés arrêtent Attila en Gaule."],
    [476, null, "Chute de l'Empire romain d'Occident", "P", "M", 1, "Le dernier empereur d'Occident est déposé."],
    [486, null, "Clovis vainc à Soissons", "G", "F", 3, "Fin du dernier pouvoir romain en Gaule."],
    [496, null, "Baptême de Clovis", "R", "F", 1, "Vers 496 : le roi des Francs se convertit au christianisme catholique."],
    [541, 549, "Peste de Justinien", "E", "M", 3, "Première grande pandémie de peste en Europe."],
    [622, null, "Hégire", "R", "M", 1, "Début de l'ère musulmane."],
    [711, null, "Conquête musulmane de l'Espagne", "G", "M", 2, "Début d'Al-Andalus."],
    [732, null, "Bataille de Poitiers", "G", "F", 1, "Charles Martel arrête une expédition venue d'Espagne."],
    [751, null, "Pépin le Bref, premier roi carolingien", "P", "F", 2, "Fin des Mérovingiens."],
    [800, null, "Charlemagne, empereur", "P", "F", 1, "Couronné empereur à Rome le jour de Noël."],
    [843, null, "Traité de Verdun", "P", "F", 2, "Partage de l'empire carolingien : naissance de la Francie occidentale."],
    [885, 886, "Siège de Paris par les Vikings", "G", "F", 3, "Épisode des raids vikings sur la Seine."],
    [911, null, "Naissance de la Normandie", "P", "F", 3, "Traité de Saint-Clair-sur-Epte avec le chef viking Rollon."],
    [987, null, "Hugues Capet roi", "P", "F", 1, "Début de la dynastie capétienne."],
    [1054, null, "Grand Schisme", "R", "M", 2, "Rupture entre les Églises de Rome et de Constantinople."],
    [1066, null, "Hastings : conquête normande", "G", "M", 1, "Guillaume le Conquérant s'empare de l'Angleterre."],
    [1096, 1099, "Première croisade", "G", "M", 1, "Prise de Jérusalem en 1099."],
    [1163, 1345, "Construction de Notre-Dame de Paris", "C", "F", 2, "Chantier de la cathédrale gothique."],
    [1204, null, "Philippe Auguste reprend la Normandie", "P", "F", 3, "Renforcement du domaine royal."],
    [1206, 1227, "Conquêtes de Gengis Khan", "G", "M", 3, "Formation de l'empire mongol."],
    [1209, 1229, "Croisade des Albigeois", "G", "F", 2, "Guerre contre les cathares du Midi."],
    [1214, null, "Bataille de Bouvines", "G", "F", 2, "Victoire de Philippe Auguste, près de Lille."],
    [1215, null, "Magna Carta", "P", "M", 2, "Charte limitant le pouvoir du roi d'Angleterre."],
    [1309, 1377, "Papes en Avignon", "R", "F", 2, "La papauté quitte Rome pour Avignon."],
    [1315, 1317, "Grande famine", "E", "M", 3, "Mauvaises récoltes et famine en Europe du Nord."],
    [1337, 1453, "Guerre de Cent Ans", "G", "F", 1, "Conflit entre les royaumes de France et d'Angleterre."],
    [1347, 1352, "Peste noire", "E", "M", 1, "Elle emporte environ un tiers des Européens."],
    [1358, null, "Jacquerie", "S", "F", 3, "Révolte paysanne dans le nord de la France."],
    [1415, null, "Azincourt", "G", "F", 2, "Défaite française face aux Anglais."],
    [1429, null, "Jeanne d'Arc à Orléans", "G", "F", 1, "Le siège d'Orléans est levé ; sacre de Charles VII."],
    [1431, null, "Mort de Jeanne d'Arc", "G", "F", 3, "Brûlée à Rouen."],
    [1450, null, "Gutenberg et l'imprimerie", "C", "M", 1, "Vers 1450 : les livres imprimés se répandent."],
    [1453, null, "Chute de Constantinople", "G", "M", 1, "Prise par les Ottomans ; fin de l'Empire byzantin."],
    [1492, null, "Colomb atteint l'Amérique", "P", "M", 1, "Début de la colonisation européenne du Nouveau Monde."],
    [1494, 1559, "Guerres d'Italie", "G", "F", 2, "Les rois de France s'affrontent aux Habsbourg."],
    [1498, null, "Vasco de Gama atteint l'Inde", "P", "M", 3, "Route maritime vers l'Asie."],
    [1515, null, "Marignan", "G", "F", 2, "Victoire de François Iᵉʳ."],
    [1517, null, "Luther et la Réforme", "R", "M", 1, "Début de la Réforme protestante."],
    [1519, 1522, "Tour du monde de Magellan", "C", "M", 3, "Première circumnavigation."],
    [1539, null, "Ordonnance de Villers-Cotterêts", "S", "F", 2, "Le français devient langue du droit ; tenue des registres de baptême."],
    [1543, null, "Copernic : héliocentrisme", "C", "M", 2, "Publication de « Des révolutions des sphères célestes »."],
    [1562, 1598, "Guerres de Religion", "G", "F", 1, "Catholiques contre protestants."],
    [1572, null, "Saint-Barthélemy", "R", "F", 1, "Massacre des protestants à Paris et en province."],
    [1582, null, "Calendrier grégorien", "S", "F", 3, "Adopté en France : le 9 décembre est suivi du 20 décembre."],
    [1598, null, "Édit de Nantes", "R", "F", 1, "Tolérance accordée aux protestants."],
    [1609, null, "Galilée et la lunette astronomique", "C", "M", 3, "Observation du ciel à la lunette."],
    [1618, 1648, "Guerre de Trente Ans", "G", "M", 1, "Conflit européen très meurtrier, dernière grande guerre de religion."],
    [1648, 1653, "La Fronde", "G", "F", 2, "Révoltes contre Mazarin et la monarchie."],
    [1678, null, "Traité de Nimègue", "P", "F", 2, "Valenciennes et le Hainaut sont rattachés à la France."],
    [1682, null, "Louis XIV s'installe à Versailles", "P", "F", 2, "Le château devient siège de la cour."],
    [1685, null, "Révocation de l'édit de Nantes", "R", "F", 1, "Fin de la tolérance envers les protestants."],
    [1687, null, "Newton : les Principia", "C", "M", 2, "Loi de la gravitation universelle."],
    [1693, 1694, "Grande famine", "E", "F", 2, "Disette et forte surmortalité en France."],
    [1701, 1714, "Guerre de Succession d'Espagne", "G", "M", 2, "Le petit-fils de Louis XIV devient roi d'Espagne."],
    [1709, null, "Grand hiver", "E", "F", 2, "Froid extrême, récoltes détruites, famine."],
    [1720, 1722, "Peste de Marseille", "E", "F", 3, "Dernière grande épidémie de peste en France."],
    [1751, 1772, "L'Encyclopédie", "C", "F", 2, "Diderot et d'Alembert diffusent les idées des Lumières."],
    [1756, 1763, "Guerre de Sept Ans", "G", "M", 2, "La France perd l'essentiel de son premier empire colonial."],
    [1769, null, "Machine à vapeur de Watt", "S", "M", 2, "Début de la révolution industrielle."],
    [1776, null, "Indépendance des États-Unis", "P", "M", 1, "La France soutiendra les insurgés à partir de 1778."],
    [1783, null, "Premiers vols en montgolfière", "C", "F", 3, "Les frères Montgolfier, puis Pilâtre de Rozier."],
    [1789, null, "Révolution française", "P", "F", 1, "Prise de la Bastille, Déclaration des droits de l'homme."],
    [1792, null, "République et état civil laïc", "P", "F", 1, "Abolition de la monarchie ; les registres d'état civil passent aux mairies."],
    [1793, 1794, "La Terreur", "P", "F", 1, "Exécution de Louis XVI en janvier 1793 puis régime d'exception."],
    [1793, 1796, "Guerre de Vendée", "G", "F", 2, "Insurrection contre la République dans l'Ouest."],
    [1796, null, "Jenner : le vaccin contre la variole", "C", "M", 3, "Premier vaccin."],
    [1799, null, "Bonaparte : coup d'État du 18 brumaire", "P", "F", 2, "Début du Consulat."],
    [1804, null, "Napoléon empereur — Code civil", "P", "F", 1, "Sacre de Napoléon Iᵉʳ ; promulgation du Code civil."],
    [1805, null, "Austerlitz", "G", "F", 2, "Grande victoire de Napoléon."],
    [1812, null, "Campagne de Russie", "G", "F", 1, "Désastre de la Grande Armée."],
    [1815, null, "Waterloo", "G", "F", 1, "Défaite finale de Napoléon."],
    [1825, null, "Premier chemin de fer à vapeur", "S", "M", 3, "Ligne Stockton–Darlington, en Angleterre."],
    [1830, null, "Trois Glorieuses — conquête d'Alger", "P", "F", 2, "Chute de Charles X ; début de la conquête de l'Algérie."],
    [1832, null, "Épidémie de choléra", "E", "F", 3, "Le choléra frappe Paris et de nombreuses villes."],
    [1842, null, "Loi sur les chemins de fer", "S", "F", 3, "Plan des grandes lignes ; le rail atteint le Nord."],
    [1848, null, "Révolution de 1848", "P", "F", 1, "Abolition de l'esclavage ; suffrage universel masculin."],
    [1853, 1870, "Travaux d'Haussmann", "S", "F", 3, "Transformation de Paris."],
    [1859, null, "Darwin : L'Origine des espèces", "C", "M", 2, "Théorie de l'évolution."],
    [1861, 1865, "Guerre de Sécession", "G", "M", 3, "Guerre civile aux États-Unis."],
    [1869, null, "Canal de Suez", "S", "M", 3, "Ouverture de la voie maritime."],
    [1870, 1871, "Guerre franco-prussienne", "G", "F", 1, "Chute du Second Empire ; annexion de l'Alsace-Moselle."],
    [1871, null, "Commune de Paris", "P", "F", 1, "Insurrection parisienne écrasée en mai."],
    [1876, null, "Le téléphone (Bell)", "C", "M", 3, "Invention du téléphone."],
    [1879, null, "L'ampoule électrique (Edison)", "C", "M", 3, "Éclairage électrique."],
    [1882, null, "Lois Jules Ferry", "S", "F", 1, "École publique gratuite, laïque et obligatoire (1881-1882)."],
    [1884, null, "Grève des mineurs d'Anzin", "S", "F", 3, "Grande grève dans le Nord minier ; loi Waldeck-Rousseau sur les syndicats."],
    [1885, null, "Pasteur : vaccin contre la rage", "C", "F", 3, "Première inoculation à un enfant."],
    [1889, null, "Exposition universelle et tour Eiffel", "C", "F", 2, "Centenaire de la Révolution."],
    [1894, 1906, "Affaire Dreyfus", "P", "F", 1, "Divise la France ; réhabilitation en 1906."],
    [1895, null, "Cinéma des frères Lumière", "C", "F", 2, "Première séance publique à Paris."],
    [1903, null, "Premier vol des frères Wright", "C", "M", 3, "Débuts de l'aviation."],
    [1905, null, "Séparation des Églises et de l'État", "R", "F", 1, "Loi de laïcité."],
    [1906, null, "Catastrophe de Courrières", "E", "F", 2, "Coup de grisou : 1 099 mineurs meurent dans le Pas-de-Calais."],
    [1914, 1918, "Première Guerre mondiale", "G", "M", 1, "Environ 1,4 million de soldats français tués."],
    [1914, 1918, "Le Nord occupé", "G", "F", 2, "Une grande partie du Nord vit sous occupation allemande."],
    [1916, null, "Bataille de Verdun", "G", "F", 2, "Dix mois de combats."],
    [1917, null, "Révolution russe", "P", "M", 1, "Prise du pouvoir par les bolcheviks."],
    [1918, 1919, "Grippe espagnole", "E", "M", 1, "Pandémie mondiale."],
    [1919, null, "Traité de Versailles", "P", "M", 2, "Fin officielle de la Première Guerre mondiale."],
    [1929, null, "Krach de Wall Street", "S", "M", 1, "Début de la Grande Dépression."],
    [1933, null, "Hitler au pouvoir", "P", "M", 2, "Installation du régime nazi."],
    [1936, null, "Front populaire — congés payés", "S", "F", 1, "Deux semaines de congés payés, semaine de 40 heures."],
    [1939, 1945, "Seconde Guerre mondiale", "G", "M", 1, "Le conflit le plus meurtrier de l'histoire."],
    [1940, null, "Défaite, occupation, appel du 18 juin", "G", "F", 1, "La France est envahie ; le régime de Vichy s'installe."],
    [1944, null, "Débarquement et Libération", "G", "F", 1, "Normandie en juin ; Paris libéré en août ; le Nord en septembre."],
    [1944, null, "Vote des femmes", "S", "F", 1, "Ordonnance d'avril 1944 ; premier vote féminin en 1945."],
    [1945, null, "Hiroshima et fin de la guerre", "G", "M", 1, "Capitulation de l'Allemagne en mai, du Japon en septembre."],
    [1945, null, "Sécurité sociale", "S", "F", 2, "Création de la Sécurité sociale."],
    [1945, 1975, "Trente Glorieuses", "S", "F", 1, "Forte croissance et essor de la société de consommation."],
    [1954, 1962, "Guerre d'Algérie", "G", "F", 1, "Conflit qui mène à l'indépendance de l'Algérie."],
    [1954, null, "Appel de l'abbé Pierre", "S", "F", 3, "Hiver 1954 : mobilisation contre le mal-logement."],
    [1957, null, "Traité de Rome", "P", "M", 2, "Naissance de la Communauté économique européenne."],
    [1957, null, "Spoutnik", "C", "M", 3, "Début de la conquête spatiale."],
    [1958, null, "Ve République", "P", "F", 1, "Retour du général de Gaulle."],
    [1968, null, "Mai 68", "S", "F", 1, "Grèves et contestation étudiante."],
    [1969, null, "Premier pas sur la Lune", "C", "M", 2, "Apollo 11."],
    [1973, null, "Premier choc pétrolier", "S", "M", 2, "Fin des Trente Glorieuses."],
    [1981, null, "Mitterrand — abolition de la peine de mort", "P", "F", 2, "Première alternance de la Ve République."],
    [1989, null, "Chute du mur de Berlin", "P", "M", 1, "Fin de la guerre froide en Europe."],
    [1991, null, "Fin de l'URSS", "P", "M", 2, "Dissolution de l'Union soviétique."],
    [1991, null, "Le Web ouvert au public", "C", "M", 3, "Début d'Internet grand public."],
    [1992, null, "Traité de Maastricht", "P", "M", 3, "Naissance de l'Union européenne."],
    [1998, null, "France championne du monde", "S", "F", 3, "Victoire en Coupe du monde de football."],
    [2001, null, "Attentats du 11 septembre", "G", "M", 1, "Attaques contre New York et Washington."],
    [2002, null, "L'euro remplace le franc", "S", "F", 2, "Entrée en circulation des pièces et billets."],
    [2008, null, "Crise financière mondiale", "S", "M", 2, "Faillite de Lehman Brothers."],
    [2015, null, "Attentats de Paris", "G", "F", 2, "13 novembre 2015."],
    [2020, 2022, "Pandémie de Covid-19", "E", "M", 1, "Confinements et campagne de vaccination."],
    [2022, null, "Guerre en Ukraine", "G", "M", 2, "Invasion de l'Ukraine par la Russie."],
  ],
  regimes: [
    [481, 751, "Mérovingiens"],
    [751, 987, "Carolingiens"],
    [987, 1328, "Capétiens directs"],
    [1328, 1589, "Valois"],
    [1589, 1789, "Bourbons — Ancien Régime"],
    [1789, 1799, "Révolution"],
    [1799, 1815, "Consulat et Ier Empire"],
    [1815, 1830, "Restauration"],
    [1830, 1848, "Monarchie de Juillet"],
    [1848, 1852, "IIᵉ République"],
    [1852, 1870, "Second Empire"],
    [1870, 1940, "IIIᵉ République"],
    [1940, 1944, "Vichy"],
    [1944, 1946, "Gouv. provisoire"],
    [1946, 1958, "IVᵉ République"],
    [1958, 2027, "Vᵉ République"],
  ],
  souverains: [
    [481, 511, "Clovis"],
    [751, 768, "Pépin le Bref"],
    [768, 814, "Charlemagne"],
    [987, 996, "Hugues Capet"],
    [996, 1031, "Robert II"],
    [1031, 1060, "Henri Iᵉʳ"],
    [1060, 1108, "Philippe Iᵉʳ"],
    [1108, 1137, "Louis VI"],
    [1137, 1180, "Louis VII"],
    [1180, 1223, "Philippe Auguste"],
    [1223, 1226, "Louis VIII"],
    [1226, 1270, "Saint Louis"],
    [1270, 1285, "Philippe III"],
    [1285, 1314, "Philippe IV le Bel"],
    [1314, 1316, "Louis X"],
    [1316, 1322, "Philippe V"],
    [1322, 1328, "Charles IV"],
    [1328, 1350, "Philippe VI"],
    [1350, 1364, "Jean II le Bon"],
    [1364, 1380, "Charles V"],
    [1380, 1422, "Charles VI"],
    [1422, 1461, "Charles VII"],
    [1461, 1483, "Louis XI"],
    [1483, 1498, "Charles VIII"],
    [1498, 1515, "Louis XII"],
    [1515, 1547, "François Iᵉʳ"],
    [1547, 1559, "Henri II"],
    [1559, 1560, "François II"],
    [1560, 1574, "Charles IX"],
    [1574, 1589, "Henri III"],
    [1589, 1610, "Henri IV"],
    [1610, 1643, "Louis XIII"],
    [1643, 1715, "Louis XIV"],
    [1715, 1774, "Louis XV"],
    [1774, 1792, "Louis XVI"],
    [1792, 1795, "Convention"],
    [1795, 1799, "Directoire"],
    [1799, 1804, "Consulat"],
    [1804, 1814, "Napoléon Iᵉʳ"],
    [1814, 1824, "Louis XVIII"],
    [1824, 1830, "Charles X"],
    [1830, 1848, "Louis-Philippe"],
    [1848, 1852, "Louis-Napoléon Bonaparte"],
    [1852, 1870, "Napoléon III"],
    [1871, 1873, "Thiers"],
    [1873, 1879, "Mac Mahon"],
    [1879, 1887, "Grévy"],
    [1887, 1894, "Carnot"],
    [1894, 1895, "Casimir-Perier"],
    [1895, 1899, "Félix Faure"],
    [1899, 1906, "Loubet"],
    [1906, 1913, "Fallières"],
    [1913, 1920, "Poincaré"],
    [1920, 1924, "Millerand"],
    [1924, 1931, "Doumergue"],
    [1931, 1932, "Doumer"],
    [1932, 1940, "Lebrun"],
    [1940, 1944, "Pétain"],
    [1944, 1946, "de Gaulle"],
    [1947, 1954, "Auriol"],
    [1954, 1959, "Coty"],
    [1959, 1969, "de Gaulle"],
    [1969, 1974, "Pompidou"],
    [1974, 1981, "Giscard d'Estaing"],
    [1981, 1995, "Mitterrand"],
    [1995, 2007, "Chirac"],
    [2007, 2012, "Sarkozy"],
    [2012, 2017, "Hollande"],
    [2017, 2027, "Macron"],
  ],
  epoques: [
    [200, 476, "Antiquité tardive"],
    [476, 1000, "Haut Moyen Âge"],
    [1000, 1300, "Moyen Âge central"],
    [1300, 1492, "Bas Moyen Âge"],
    [1492, 1600, "Renaissance et Réformes"],
    [1600, 1715, "Grand Siècle"],
    [1715, 1789, "Lumières"],
    [1789, 1815, "Révolutions et Empire"],
    [1815, 1870, "Révolution industrielle"],
    [1870, 1914, "Belle Époque"],
    [1914, 1945, "Guerres mondiales"],
    [1945, 1991, "Guerre froide"],
    [1991, 2027, "Époque contemporaine"],
  ],
};
